McmtSingleDetectNode:
  ros__parameters:
    IS_REALTIME: False
    VIDEO_INPUT: "/home/mcmt/spot-it-3d/mcmt-tracking/footage/G.mp4"
    FRAME_WIDTH: 1920
    FRAME_HEIGHT: 1080
    VIDEO_FPS: 30
    MAX_TOLERATED_CONSECUTIVE_DROPPED_FRAMES: 5
    VISIBILITY_RATIO: 0.8
    VISIBILITY_THRESH: 1.0
    CONSECUTIVE_THRESH: 1.0
    AGE_THRESH: 1.0
    SECONDARY_FILTER: 2
    SEC_FILTER_DELAY: 1.0
    FGBG_HISTORY: 5
    BACKGROUND_RATIO: 0.05
    NMIXTURES: 5
    BRIGHTNESS_GAIN: 15
    FGBG_LEARNING_RATE: 0.2
    DILATION_ITER: 2
    REMOVE_GROUND_ITER: 5.75
    BACKGROUND_CONTOUR_CIRCULARITY: 0.5

McmtMultiDetectNode:
  ros__parameters:
    IS_REALTIME: True
    VIDEO_INPUT_1: "/home/mcmt/spot-it-3d/mcmt-tracking/footage/A.mp4"
    VIDEO_INPUT_2: "/home/mcmt/spot-it-3d/mcmt-tracking/footage/B.mp4"
    FRAME_WIDTH: 1920
    FRAME_HEIGHT: 1080
    VIDEO_FPS: 30
    MAX_TOLERATED_CONSECUTIVE_DROPPED_FRAMES: 5
    VISIBILITY_RATIO: 0.8
    VISIBILITY_THRESH: 1.0
    CONSECUTIVE_THRESH: 1.0
    AGE_THRESH: 1.0
    SECONDARY_FILTER: 2
    SEC_FILTER_DELAY: 1.0
    FGBG_HISTORY: 5
    BACKGROUND_RATIO: 0.05
    NMIXTURES: 5
    BRIGHTNESS_GAIN: 15
    FGBG_LEARNING_RATE: 0.2
    DILATION_ITER: 2
    REMOVE_GROUND_ITER: 5.75
    BACKGROUND_CONTOUR_CIRCULARITY: 0.5

SingleTrackerNode:
  ros__parameters:
    IS_REALTIME: False
    VIDEO_INPUT: "/home/mcmt/spot-it-3d/mcmt-tracking/footage/G.mp4"
    FRAME_WIDTH: 1920
    FRAME_HEIGHT: 1080
    OUTPUT_VIDEO_PATH: "/home/mcmt/spot-it-3d/data/video_plot.avi"
    OUTPUT_CSV_PATH: "/home/mcmt/spot-it-3d/data/data_out.csv"

MultiTrackerNode:
  ros__parameters:
    IS_REALTIME: True
    VIDEO_INPUT_1: "/home/mcmt/spot-it-3d/mcmt-tracking/footage/A.mp4"
    VIDEO_INPUT_2: "/home/mcmt/spot-it-3d/mcmt-tracking/footage/B.mp4"
    FRAME_WIDTH: 1920
    FRAME_HEIGHT: 1080
    OUTPUT_VIDEO_PATH: "/home/mcmt/spot-it-3d/data/video_plot.avi"
    OUTPUT_CSV_PATH_1: "/home/mcmt/spot-it-3d/data/data_out_0.csv"
    OUTPUT_CSV_PATH_2: "/home/mcmt/spot-it-3d/data/data_out_0.csv"