version: '3.3'

services:
  mcmt-detector:
    build:
      dockerfile: ./mcmt-dockerfiles/Dockerfile.mcmt
      context: ..
    image: spotit3d/mcmt:mcmt
    network_mode: "host"
    environment:
      - DISPLAY=172.24.128.1:0.0
    volumes:
      # - /home/mcmt/mcmt-docker/
      - ../data:/home/mcmt/spot-it-3d/data/
    stop_signal: SIGINT
    command: bash -c "cd spot-it-3d/mcmt-tracking/bin && sleep 5 && ./mcmt_multi_detector.sh"
  
  mcmt-tracker:
    build:
      dockerfile: ./mcmt-dockerfiles/Dockerfile.mcmt
      context: ..
    image: spotit3d/mcmt:mcmt
    network_mode: "host"
    environment:
      - DISPLAY=172.24.128.1:0.0
    volumes:
      # - /home/mcmt/mcmt-docker/
      - ../data:/home/mcmt/spot-it-3d/data/
    stop_signal: SIGINT
    command: bash -c "cd spot-it-3d/mcmt-tracking/bin && ./mcmt_multi_track.sh"
    